# Generated by Django 4.0.3 on 2022-03-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Valor Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('Metros', 'MT'), ('Unidade', 'UN'), ('Metro Cubico', 'M3'), ('Metro Quadrado', 'M2'), ('Quilo', 'KG'), ('Tonelada', 'TO'), ('Conjunto', 'CJ'), ('Peça', 'PC'), ('Pacote', 'PT')], max_length=14, verbose_name='Unidade de Medida'),
        ),
    ]
