# Generated by Django 4.0.3 on 2022-04-11 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_entrada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
