# Generated by Django 4.0.3 on 2022-03-21 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_produto_total_alter_produto_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='total',
        ),
    ]
